apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: {{ namespace }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: {{ image }}
        ports:
        - containerPort: 80

