apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ak
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: docker.io/bluffmaster32/development-development:tomcat10-untested-1
        envFrom:
        - configMapRef:
            name: nginx-cm
        - secretRef:
            name: nginx-secret
        ports:
        - containerPort: 80


