VAGRANTFILE_API_VERSION = "2"

NODES = {
  "master" => "192.168.56.10",
  "worker1" => "192.168.56.11",
  "worker2" => "192.168.56.12"
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  
  NODES.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.provision "shell", path: "scripts/common.sh"
      if name == "master"
        node.vm.provision "shell", path: "scripts/master.sh"
		node.vm.network "forwarded_port", guest: 30080, host: 30080
      else
        node.vm.provision "shell", path: "scripts/worker.sh", env: {
          "MASTER_IP" => NODES["master"]
        }
      end
    end
  end
end

