---

- name: Synchronize .kube config from server A to B
  synchronize:
    src:  ~/.kube
    dest:  ~/.kube
  delegate_to: localhost

- name: creation of namespace
  command: kubectl create ns {{ namespace }}

- name: Copy deploy.yml from build_node to deploy_node
  synchronize:
    src: "{{ item }}.yml"
    dest: "/tmp/files/{{ item }}.yml"
  delegate_to: localhost
  loop:
    - deploy
    - svc

- name: Deploying the image
  command: kubectl apply -f /tmp/files/deploy.yml

- name: Deploying the service
  command: kubectl apply -f /tmp/files/svc.yml
